# Generated by Django 4.1.7 on 2023-06-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cadastro',
            fields=[
                ('id_cadastro', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=100)),
                ('idade', models.IntegerField(max_length=3)),
                ('cpf', models.IntegerField(max_length=11)),
                ('cnh', models.IntegerField(max_length=20)),
            ],
        ),
    ]
