# Generated by Django 4.1.7 on 2023-06-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_aluguel_carro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='cnh',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='cpf',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='idade',
            field=models.IntegerField(),
        ),
    ]
