# Generated by Django 4.1.7 on 2023-06-18 21:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_aluguel_carro', '0002_alter_cadastro_cnh_alter_cadastro_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='gmail',
            field=models.TextField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
