# Generated by Django 4.1.7 on 2023-06-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_aluguel_carro', '0003_cadastro_gmail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastros',
            fields=[
                ('id_cadastro', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=100)),
                ('idade', models.IntegerField()),
                ('gmail', models.TextField(max_length=200)),
                ('cpf', models.IntegerField()),
                ('cnh', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='cadastro',
        ),
    ]
