# Generated by Django 4.1.7 on 2023-06-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_aluguel_carro', '0004_cadastros_delete_cadastro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferencias',
            fields=[
                ('id_preferencias', models.AutoField(primary_key=True, serialize=False)),
                ('cidade_retirada', models.TextField(max_length=100)),
                ('dia_retirada', models.IntegerField()),
                ('dia_devolução', models.IntegerField()),
                ('tamanho', models.TextField(max_length=1)),
                ('cor', models.TextField(max_length=50)),
            ],
        ),
    ]
