# Generated by Django 4.1.7 on 2023-09-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_aluguel_carro", "0005_preferencias"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.TextField(max_length=100)),
                ("model", models.TextField(max_length=200)),
                ("brand", models.TextField(max_length=200)),
                ("year", models.IntegerField()),
                ("rented", models.BooleanField(default=False)),
                ("rented_at", models.DateTimeField()),
                ("rented_until", models.DateTimeField()),
                ("picture", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="Cadastros",
        ),
        migrations.DeleteModel(
            name="Preferencias",
        ),
    ]
