# Generated by Django 4.1.7 on 2023-09-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_aluguel_carro", "0006_car_delete_cadastros_delete_preferencias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="rented_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="rented_until",
            field=models.DateTimeField(null=True),
        ),
    ]
